version: '3.9'

services:
  web:
    build: .
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=production
    # Optionally mount the local build directory for iterative development
    # volumes:
    #   - ./dist:/usr/share/nginx/html